export const BLOOD_GROUPS_OPTIONS = [
    { id: 'blood_group_selection', label: 'A+' },
    { id: 'blood_group_selection', label: 'A-' },
    { id: 'blood_group_selection', label: 'B+' },
    { id: 'blood_group_selection', label: 'B-' },
    { id: 'blood_group_selection', label: 'AB+' },
    { id: 'blood_group_selection', label: 'AB-' },
    { id: 'blood_group_selection', label: 'O+' },
    { id: 'blood_group_selection', label: 'O-' },
    { id: 'blood_group_selection', label: 'Unknown' },
];
export const GENDER_OPTIONS = [
    { id: 'gender_selection', label: 'Male' },
    { id: 'gender_selection', label: 'Female' },
    { id: 'gender_selection', label: 'other' },
];
export const ROLES_OPTIONS = [
    { id: 'role_selection', label: 'Patient' },
    { id: 'role_selection', label: 'Doctor' },
    { id: 'role_selection', label: 'Admin' },
];

export const PATIENT_VISIT_STATUSES = [
    { id: 'status_selection', label: 'Waiting'},
    { id: 'status_selection', label: 'Checked in'},
    { id: 'status_selection', label: 'Checked out'},
    { id: 'status_selection', label: 'Emergency'},
]

export const classNameColors = [
    'dark',
    'primary',
    'warning',
    'success',
    'danger',
]

export const FEDRAL_CITIES = [
    { id: "city_selection", label: "Islamabad" },
]

export const PUNJAB_CITIES = [
    { id: "city_selection", label: "Ahmed Nager Chatha" },
    { id: "city_selection", label: "Ahmadpur East" },
    { id: "city_selection", label: "Ali Khan Abad" },
    { id: "city_selection", label: "Alipur" },
    { id: "city_selection", label: "Arifwala" },
    { id: "city_selection", label: "Attock" },
    { id: "city_selection", label: "Bhera" },
    { id: "city_selection", label: "Bhalwal" },
    { id: "city_selection", label: "Bahawalnagar" },
    { id: "city_selection", label: "Bahawalpur" },
    { id: "city_selection", label: "Bhakkar" },
    { id: "city_selection", label: "Burewala" },
    { id: "city_selection", label: "Chillianwala" },
    { id: "city_selection", label: "Chakwal" },
    { id: "city_selection", label: "Chichawatni" },
    { id: "city_selection", label: "Chiniot" },
    { id: "city_selection", label: "Chishtian" },
    { id: "city_selection", label: "Daska" },
    { id: "city_selection", label: "Darya Khan" },
    { id: "city_selection", label: "Dera Ghazi Khan" },
    { id: "city_selection", label: "Dhaular" },
    { id: "city_selection", label: "Dina" },
    { id: "city_selection", label: "Dinga" },
    { id: "city_selection", label: "Dipalpur" },
    { id: "city_selection", label: "Faisalabad" },
    { id: "city_selection", label: "Fateh Jang" },
    { id: "city_selection", label: "Ghakhar Mandi" },
    { id: "city_selection", label: "Gojra" },
    { id: "city_selection", label: "Gujranwala" },
    { id: "city_selection", label: "Gujrat" },
    { id: "city_selection", label: "Gujar Khan" },
    { id: "city_selection", label: "Hafizabad" },
    { id: "city_selection", label: "Haroonabad" },
    { id: "city_selection", label: "Hasilpur" },
    { id: "city_selection", label: "Haveli" },
    { id: "city_selection", label: "Lakha" },
    { id: "city_selection", label: "Jalalpur" },
    { id: "city_selection", label: "Jattan" },
    { id: "city_selection", label: "Jampur" },
    { id: "city_selection", label: "Jaranwala" },
    { id: "city_selection", label: "Jhang" },
    { id: "city_selection", label: "Jhelum" },
    { id: "city_selection", label: "Kalabagh" },
    { id: "city_selection", label: "Karor Lal Esan" },
    { id: "city_selection", label: "Kasur" },
    { id: "city_selection", label: "Kamalia" },
    { id: "city_selection", label: "Kamoke" },
    { id: "city_selection", label: "Khanewal" },
    { id: "city_selection", label: "Khanpur" },
    { id: "city_selection", label: "Kharian" },
    { id: "city_selection", label: "Khushab" },
    { id: "city_selection", label: "Kot Adu" },
    { id: "city_selection", label: "Jauharabad" },
    { id: "city_selection", label: "Lahore" },
    { id: "city_selection", label: "Lalamusa" },
    { id: "city_selection", label: "Layyah" },
    { id: "city_selection", label: "Liaquat Pur" },
    { id: "city_selection", label: "Lodhran" },
    { id: "city_selection", label: "Malakwal" },
    { id: "city_selection", label: "Mamoori" },
    { id: "city_selection", label: "Mailsi" },
    { id: "city_selection", label: "Mandi Bahauddin" },
    { id: "city_selection", label: "Mian Channu" },
    { id: "city_selection", label: "Mianwali" },
    { id: "city_selection", label: "Multan" },
    { id: "city_selection", label: "Murree" },
    { id: "city_selection", label: "Muridke" },
    { id: "city_selection", label: "Mianwali Bangla" },
    { id: "city_selection", label: "Muzaffargarh" },
    { id: "city_selection", label: "Narowal" },
    { id: "city_selection", label: "Okara" },
    { id: "city_selection", label: "Renala Khurd" },
    { id: "city_selection", label: "Pakpattan" },
    { id: "city_selection", label: "Pattoki" },
    { id: "city_selection", label: "Pir Mahal" },
    { id: "city_selection", label: "Qaimpur" },
    { id: "city_selection", label: "Qila Didar Singh" },
    { id: "city_selection", label: "Rabwah" },
    { id: "city_selection", label: "Raiwind" },
    { id: "city_selection", label: "Rajanpur" },
    { id: "city_selection", label: "Rahim Yar Khan" },
    { id: "city_selection", label: "Rawalpindi" },
    { id: "city_selection", label: "Sadiqabad" },
    { id: "city_selection", label: "Safdarabad" },
    { id: "city_selection", label: "Sahiwal" },
    { id: "city_selection", label: "Sangla Hill" },
    { id: "city_selection", label: "Sarai Alamgir" },
    { id: "city_selection", label: "Sargodha" },
    { id: "city_selection", label: "Shakargarh" },
    { id: "city_selection", label: "Sheikhupura" },
    { id: "city_selection", label: "Sialkot" },
    { id: "city_selection", label: "Sohawa" },
    { id: "city_selection", label: "Soianwala" },
    { id: "city_selection", label: "Siranwali" },
    { id: "city_selection", label: "Talagang" },
    { id: "city_selection", label: "Taxila" },
    { id: "city_selection", label: "Toba Tek Singh" },
    { id: "city_selection", label: "Vehari" },
    { id: "city_selection", label: "Wah Cantonment" },
    { id: "city_selection", label: "Wazirabad" },
]

export const SINDH_CITIES = [
    { id: "city_selection", label: "Badin" },
    { id: "city_selection", label: "Bhirkan" },
    { id: "city_selection", label: "Rajo Khanani" },
    { id: "city_selection", label: "Chak" },
    { id: "city_selection", label: "Dadu" },
    { id: "city_selection", label: "Digri" },
    { id: "city_selection", label: "Diplo" },
    { id: "city_selection", label: "Dokri" },
    { id: "city_selection", label: "Ghotki" },
    { id: "city_selection", label: "Haala" },
    { id: "city_selection", label: "Hyderabad" },
    { id: "city_selection", label: "Islamkot" },
    { id: "city_selection", label: "Jacobabad" },
    { id: "city_selection", label: "Jamshoro" },
    { id: "city_selection", label: "Jungshahi" },
    { id: "city_selection", label: "Kandhkot" },
    { id: "city_selection", label: "Kandiaro" },
    { id: "city_selection", label: "Karachi" },
    { id: "city_selection", label: "Kashmore" },
    { id: "city_selection", label: "Keti Bandar" },
    { id: "city_selection", label: "Khairpur" },
    { id: "city_selection", label: "Kotri" },
    { id: "city_selection", label: "Larkana" },
    { id: "city_selection", label: "Matiari" },
    { id: "city_selection", label: "Mehar" },
    { id: "city_selection", label: "Mirpur Khas" },
    { id: "city_selection", label: "Mithani" },
    { id: "city_selection", label: "Mithi" },
    { id: "city_selection", label: "Mehrabpur" },
    { id: "city_selection", label: "Moro" },
    { id: "city_selection", label: "Nagarparkar" },
    { id: "city_selection", label: "Naudero" },
    { id: "city_selection", label: "Naushahro Feroze" },
    { id: "city_selection", label: "Naushara" },
    { id: "city_selection", label: "Nawabshah" },
    { id: "city_selection", label: "Nazimabad" },
    { id: "city_selection", label: "Qambar" },
    { id: "city_selection", label: "Qasimabad" },
    { id: "city_selection", label: "Ranipur" },
    { id: "city_selection", label: "Ratodero" },
    { id: "city_selection", label: "Rohri" },
    { id: "city_selection", label: "Sakrand" },
    { id: "city_selection", label: "Sanghar" },
    { id: "city_selection", label: "Shahbandar" },
    { id: "city_selection", label: "Shahdadkot" },
    { id: "city_selection", label: "Shahdadpur" },
    { id: "city_selection", label: "Shahpur Chakar" },
    { id: "city_selection", label: "Shikarpaur" },
    { id: "city_selection", label: "Sukkur" },
    { id: "city_selection", label: "Tangwani" },
    { id: "city_selection", label: "Tando Adam Khan" },
    { id: "city_selection", label: "Tando Allahyar" },
    { id: "city_selection", label: "Tando Muhammad Khan" },
    { id: "city_selection", label: "Thatta" },
    { id: "city_selection", label: "Umerkot" },
    { id: "city_selection", label: "Warah" },
]

export const KPK_CITIES = [
    { id: "city_selection", label: "Abbottabad" },
    { id: "city_selection", label: "Adezai" },
    { id: "city_selection", label: "Alpuri" },
    { id: "city_selection", label: "Akora Khattak" },
    { id: "city_selection", label: "Ayubia" },
    { id: "city_selection", label: "Banda Daud Shah" },
    { id: "city_selection", label: "Bannu" },
    { id: "city_selection", label: "Batkhela" },
    { id: "city_selection", label: "Battagram" },
    { id: "city_selection", label: "Birote" },
    { id: "city_selection", label: "Chakdara" },
    { id: "city_selection", label: "Charsadda" },
    { id: "city_selection", label: "Chitral" },
    { id: "city_selection", label: "Daggar" },
    { id: "city_selection", label: "Dargai" },
    { id: "city_selection", label: "Darya Khan" },
    { id: "city_selection", label: "Dera Ismail Khan" },
    { id: "city_selection", label: "Doaba" },
    { id: "city_selection", label: "Dir" },
    { id: "city_selection", label: "Drosh" },
    { id: "city_selection", label: "Hangu" },
    { id: "city_selection", label: "Haripur" },
    { id: "city_selection", label: "Karak" },
    { id: "city_selection", label: "Kohat" },
    { id: "city_selection", label: "Kulachi" },
    { id: "city_selection", label: "Lakki Marwat" },
    { id: "city_selection", label: "Latamber" },
    { id: "city_selection", label: "Madyan" },
    { id: "city_selection", label: "Mansehra" },
    { id: "city_selection", label: "Mardan" },
    { id: "city_selection", label: "Mastuj" },
    { id: "city_selection", label: "Mingora" },
    { id: "city_selection", label: "Nowshera" },
    { id: "city_selection", label: "Paharpur" },
    { id: "city_selection", label: "Pabbi" },
    { id: "city_selection", label: "Peshawar" },
    { id: "city_selection", label: "Saidu Sharif" },
    { id: "city_selection", label: "Shorkot" },
    { id: "city_selection", label: "Shewa Adda" },
    { id: "city_selection", label: "Swabi" },
    { id: "city_selection", label: "Swat" },
    { id: "city_selection", label: "Tangi" },
    { id: "city_selection", label: "Tank" },
    { id: "city_selection", label: "Thall" },
    { id: "city_selection", label: "Timergara" },
    { id: "city_selection", label: "Tordher" },
]

export const BALOCHISTAN_CITIES = [
    { id: "city_selection", label: "Awaran" },
    { id: "city_selection", label: "Barkhan" },
    { id: "city_selection", label: "Chagai" },
    { id: "city_selection", label: "Dera Bugti" },
    { id: "city_selection", label: "Gwadar" },
    { id: "city_selection", label: "Harnai" },
    { id: "city_selection", label: "Jafarabad" },
    { id: "city_selection", label: "Jhal Magsi" },
    { id: "city_selection", label: "Kacchi" },
    { id: "city_selection", label: "Kalat" },
    { id: "city_selection", label: "Kech" },
    { id: "city_selection", label: "Kharan" },
    { id: "city_selection", label: "Khuzdar" },
    { id: "city_selection", label: "Killa Abdullah" },
    { id: "city_selection", label: "Killa Saifullah" },
    { id: "city_selection", label: "Kohlu" },
    { id: "city_selection", label: "Lasbela" },
    { id: "city_selection", label: "Lehri" },
    { id: "city_selection", label: "Loralai" },
    { id: "city_selection", label: "Mastung" },
    { id: "city_selection", label: "Musakhel" },
    { id: "city_selection", label: "Nasirabad" },
    { id: "city_selection", label: "Nushki" },
    { id: "city_selection", label: "Panjgur" },
    { id: "city_selection", label: "Pishin Valley" },
    { id: "city_selection", label: "Quetta" },
    { id: "city_selection", label: "Sherani" },
    { id: "city_selection", label: "Sibi" },
    { id: "city_selection", label: "Sohbatpur" },
    { id: "city_selection", label: "Washuk" },
    { id: "city_selection", label: "Zhob" },
    { id: "city_selection", label: "Ziarat" },
]

export const CITIES = [
    { label: 'fedral', options: FEDRAL_CITIES },
    { label: 'punjab', options: PUNJAB_CITIES },
    { label: 'sindh', options: SINDH_CITIES },
    { label: 'kpk', options: KPK_CITIES },
    { label: 'balochistan', options: BALOCHISTAN_CITIES },
]