export const BLOOD_GROUPS_OPTIONS = [
    { id: 'blood_group_selection', label: 'A+' },
    { id: 'blood_group_selection', label: 'A-' },
    { id: 'blood_group_selection', label: 'B+' },
    { id: 'blood_group_selection', label: 'B-' },
    { id: 'blood_group_selection', label: 'AB+' },
    { id: 'blood_group_selection', label: 'AB-' },
    { id: 'blood_group_selection', label: 'O+' },
    { id: 'blood_group_selection', label: 'O-' },
    { id: 'blood_group_selection', label: 'Unknown' },
];
export const GENDER_OPTIONS = [
    { id: 'gender_selection', label: 'Male' },
    { id: 'gender_selection', label: 'Female' },
    { id: 'gender_selection', label: 'other' },
];
export const ROLES_OPTIONS = [
    { id: 'role_selection', label: 'Patient' },
    { id: 'role_selection', label: 'Doctor' },
    { id: 'role_selection', label: 'Admin' },
];

export const PATIENT_VISIT_STATUSES = [
    { id: 'status_selection', label: 'Scheduled'},
    { id: 'status_selection', label: 'Waiting'},
    { id: 'status_selection', label: 'Checked in'},
    { id: 'status_selection', label: 'Checked out'},
    { id: 'status_selection', label: 'Emergency'},
]

export const classNameColors = [
    'dark',
    'primary',
    'warning',
    'success',
    'danger',
]

export const FEDRAL_CITIES = [
    { id: "city_selection", label: "Islamabad" },
]

export const PUNJAB_CITIES = [
    { id: "city_selection", label: "Ahmed Nager Chatha" },
    { id: "city_selection", label: "Ahmadpur East" },
    { id: "city_selection", label: "Ali Khan Abad" },
    { id: "city_selection", label: "Alipur" },
    { id: "city_selection", label: "Arifwala" },
    { id: "city_selection", label: "Attock" },
    { id: "city_selection", label: "Bhera" },
    { id: "city_selection", label: "Bhalwal" },
    { id: "city_selection", label: "Bahawalnagar" },
    { id: "city_selection", label: "Bahawalpur" },
    { id: "city_selection", label: "Bhakkar" },
    { id: "city_selection", label: "Burewala" },
    { id: "city_selection", label: "Chillianwala" },
    { id: "city_selection", label: "Chakwal" },
    { id: "city_selection", label: "Chichawatni" },
    { id: "city_selection", label: "Chiniot" },
    { id: "city_selection", label: "Chishtian" },
    { id: "city_selection", label: "Daska" },
    { id: "city_selection", label: "Darya Khan" },
    { id: "city_selection", label: "Dera Ghazi Khan" },
    { id: "city_selection", label: "Dhaular" },
    { id: "city_selection", label: "Dina" },
    { id: "city_selection", label: "Dinga" },
    { id: "city_selection", label: "Dipalpur" },
    { id: "city_selection", label: "Faisalabad" },
    { id: "city_selection", label: "Fateh Jang" },
    { id: "city_selection", label: "Ghakhar Mandi" },
    { id: "city_selection", label: "Gojra" },
    { id: "city_selection", label: "Gujranwala" },
    { id: "city_selection", label: "Gujrat" },
    { id: "city_selection", label: "Gujar Khan" },
    { id: "city_selection", label: "Hafizabad" },
    { id: "city_selection", label: "Haroonabad" },
    { id: "city_selection", label: "Hasilpur" },
    { id: "city_selection", label: "Haveli" },
    { id: "city_selection", label: "Lakha" },
    { id: "city_selection", label: "Jalalpur" },
    { id: "city_selection", label: "Jattan" },
    { id: "city_selection", label: "Jampur" },
    { id: "city_selection", label: "Jaranwala" },
    { id: "city_selection", label: "Jhang" },
    { id: "city_selection", label: "Jhelum" },
    { id: "city_selection", label: "Kalabagh" },
    { id: "city_selection", label: "Karor Lal Esan" },
    { id: "city_selection", label: "Kasur" },
    { id: "city_selection", label: "Kamalia" },
    { id: "city_selection", label: "Kamoke" },
    { id: "city_selection", label: "Khanewal" },
    { id: "city_selection", label: "Khanpur" },
    { id: "city_selection", label: "Kharian" },
    { id: "city_selection", label: "Khushab" },
    { id: "city_selection", label: "Kot Adu" },
    { id: "city_selection", label: "Jauharabad" },
    { id: "city_selection", label: "Lahore" },
    { id: "city_selection", label: "Lalamusa" },
    { id: "city_selection", label: "Layyah" },
    { id: "city_selection", label: "Liaquat Pur" },
    { id: "city_selection", label: "Lodhran" },
    { id: "city_selection", label: "Malakwal" },
    { id: "city_selection", label: "Mamoori" },
    { id: "city_selection", label: "Mailsi" },
    { id: "city_selection", label: "Mandi Bahauddin" },
    { id: "city_selection", label: "Mian Channu" },
    { id: "city_selection", label: "Mianwali" },
    { id: "city_selection", label: "Multan" },
    { id: "city_selection", label: "Murree" },
    { id: "city_selection", label: "Muridke" },
    { id: "city_selection", label: "Mianwali Bangla" },
    { id: "city_selection", label: "Muzaffargarh" },
    { id: "city_selection", label: "Narowal" },
    { id: "city_selection", label: "Okara" },
    { id: "city_selection", label: "Renala Khurd" },
    { id: "city_selection", label: "Pakpattan" },
    { id: "city_selection", label: "Pattoki" },
    { id: "city_selection", label: "Pir Mahal" },
    { id: "city_selection", label: "Qaimpur" },
    { id: "city_selection", label: "Qila Didar Singh" },
    { id: "city_selection", label: "Rabwah" },
    { id: "city_selection", label: "Raiwind" },
    { id: "city_selection", label: "Rajanpur" },
    { id: "city_selection", label: "Rahim Yar Khan" },
    { id: "city_selection", label: "Rawalpindi" },
    { id: "city_selection", label: "Sadiqabad" },
    { id: "city_selection", label: "Safdarabad" },
    { id: "city_selection", label: "Sahiwal" },
    { id: "city_selection", label: "Sangla Hill" },
    { id: "city_selection", label: "Sarai Alamgir" },
    { id: "city_selection", label: "Sargodha" },
    { id: "city_selection", label: "Shakargarh" },
    { id: "city_selection", label: "Sheikhupura" },
    { id: "city_selection", label: "Sialkot" },
    { id: "city_selection", label: "Sohawa" },
    { id: "city_selection", label: "Soianwala" },
    { id: "city_selection", label: "Siranwali" },
    { id: "city_selection", label: "Talagang" },
    { id: "city_selection", label: "Taxila" },
    { id: "city_selection", label: "Toba Tek Singh" },
    { id: "city_selection", label: "Vehari" },
    { id: "city_selection", label: "Wah Cantonment" },
    { id: "city_selection", label: "Wazirabad" },
]

export const SINDH_CITIES = [
    { id: "city_selection", label: "Badin" },
    { id: "city_selection", label: "Bhirkan" },
    { id: "city_selection", label: "Rajo Khanani" },
    { id: "city_selection", label: "Chak" },
    { id: "city_selection", label: "Dadu" },
    { id: "city_selection", label: "Digri" },
    { id: "city_selection", label: "Diplo" },
    { id: "city_selection", label: "Dokri" },
    { id: "city_selection", label: "Ghotki" },
    { id: "city_selection", label: "Haala" },
    { id: "city_selection", label: "Hyderabad" },
    { id: "city_selection", label: "Islamkot" },
    { id: "city_selection", label: "Jacobabad" },
    { id: "city_selection", label: "Jamshoro" },
    { id: "city_selection", label: "Jungshahi" },
    { id: "city_selection", label: "Kandhkot" },
    { id: "city_selection", label: "Kandiaro" },
    { id: "city_selection", label: "Karachi" },
    { id: "city_selection", label: "Kashmore" },
    { id: "city_selection", label: "Keti Bandar" },
    { id: "city_selection", label: "Khairpur" },
    { id: "city_selection", label: "Kotri" },
    { id: "city_selection", label: "Larkana" },
    { id: "city_selection", label: "Matiari" },
    { id: "city_selection", label: "Mehar" },
    { id: "city_selection", label: "Mirpur Khas" },
    { id: "city_selection", label: "Mithani" },
    { id: "city_selection", label: "Mithi" },
    { id: "city_selection", label: "Mehrabpur" },
    { id: "city_selection", label: "Moro" },
    { id: "city_selection", label: "Nagarparkar" },
    { id: "city_selection", label: "Naudero" },
    { id: "city_selection", label: "Naushahro Feroze" },
    { id: "city_selection", label: "Naushara" },
    { id: "city_selection", label: "Nawabshah" },
    { id: "city_selection", label: "Nazimabad" },
    { id: "city_selection", label: "Qambar" },
    { id: "city_selection", label: "Qasimabad" },
    { id: "city_selection", label: "Ranipur" },
    { id: "city_selection", label: "Ratodero" },
    { id: "city_selection", label: "Rohri" },
    { id: "city_selection", label: "Sakrand" },
    { id: "city_selection", label: "Sanghar" },
    { id: "city_selection", label: "Shahbandar" },
    { id: "city_selection", label: "Shahdadkot" },
    { id: "city_selection", label: "Shahdadpur" },
    { id: "city_selection", label: "Shahpur Chakar" },
    { id: "city_selection", label: "Shikarpaur" },
    { id: "city_selection", label: "Sukkur" },
    { id: "city_selection", label: "Tangwani" },
    { id: "city_selection", label: "Tando Adam Khan" },
    { id: "city_selection", label: "Tando Allahyar" },
    { id: "city_selection", label: "Tando Muhammad Khan" },
    { id: "city_selection", label: "Thatta" },
    { id: "city_selection", label: "Umerkot" },
    { id: "city_selection", label: "Warah" },
]

export const KPK_CITIES = [
    { id: "city_selection", label: "Abbottabad" },
    { id: "city_selection", label: "Adezai" },
    { id: "city_selection", label: "Alpuri" },
    { id: "city_selection", label: "Akora Khattak" },
    { id: "city_selection", label: "Ayubia" },
    { id: "city_selection", label: "Banda Daud Shah" },
    { id: "city_selection", label: "Bannu" },
    { id: "city_selection", label: "Batkhela" },
    { id: "city_selection", label: "Battagram" },
    { id: "city_selection", label: "Birote" },
    { id: "city_selection", label: "Chakdara" },
    { id: "city_selection", label: "Charsadda" },
    { id: "city_selection", label: "Chitral" },
    { id: "city_selection", label: "Daggar" },
    { id: "city_selection", label: "Dargai" },
    { id: "city_selection", label: "Darya Khan" },
    { id: "city_selection", label: "Dera Ismail Khan" },
    { id: "city_selection", label: "Doaba" },
    { id: "city_selection", label: "Dir" },
    { id: "city_selection", label: "Drosh" },
    { id: "city_selection", label: "Hangu" },
    { id: "city_selection", label: "Haripur" },
    { id: "city_selection", label: "Karak" },
    { id: "city_selection", label: "Kohat" },
    { id: "city_selection", label: "Kulachi" },
    { id: "city_selection", label: "Lakki Marwat" },
    { id: "city_selection", label: "Latamber" },
    { id: "city_selection", label: "Madyan" },
    { id: "city_selection", label: "Mansehra" },
    { id: "city_selection", label: "Mardan" },
    { id: "city_selection", label: "Mastuj" },
    { id: "city_selection", label: "Mingora" },
    { id: "city_selection", label: "Nowshera" },
    { id: "city_selection", label: "Paharpur" },
    { id: "city_selection", label: "Pabbi" },
    { id: "city_selection", label: "Peshawar" },
    { id: "city_selection", label: "Saidu Sharif" },
    { id: "city_selection", label: "Shorkot" },
    { id: "city_selection", label: "Shewa Adda" },
    { id: "city_selection", label: "Swabi" },
    { id: "city_selection", label: "Swat" },
    { id: "city_selection", label: "Tangi" },
    { id: "city_selection", label: "Tank" },
    { id: "city_selection", label: "Thall" },
    { id: "city_selection", label: "Timergara" },
    { id: "city_selection", label: "Tordher" },
]

export const BALOCHISTAN_CITIES = [
    { id: "city_selection", label: "Awaran" },
    { id: "city_selection", label: "Barkhan" },
    { id: "city_selection", label: "Chagai" },
    { id: "city_selection", label: "Dera Bugti" },
    { id: "city_selection", label: "Gwadar" },
    { id: "city_selection", label: "Harnai" },
    { id: "city_selection", label: "Jafarabad" },
    { id: "city_selection", label: "Jhal Magsi" },
    { id: "city_selection", label: "Kacchi" },
    { id: "city_selection", label: "Kalat" },
    { id: "city_selection", label: "Kech" },
    { id: "city_selection", label: "Kharan" },
    { id: "city_selection", label: "Khuzdar" },
    { id: "city_selection", label: "Killa Abdullah" },
    { id: "city_selection", label: "Killa Saifullah" },
    { id: "city_selection", label: "Kohlu" },
    { id: "city_selection", label: "Lasbela" },
    { id: "city_selection", label: "Lehri" },
    { id: "city_selection", label: "Loralai" },
    { id: "city_selection", label: "Mastung" },
    { id: "city_selection", label: "Musakhel" },
    { id: "city_selection", label: "Nasirabad" },
    { id: "city_selection", label: "Nushki" },
    { id: "city_selection", label: "Panjgur" },
    { id: "city_selection", label: "Pishin Valley" },
    { id: "city_selection", label: "Quetta" },
    { id: "city_selection", label: "Sherani" },
    { id: "city_selection", label: "Sibi" },
    { id: "city_selection", label: "Sohbatpur" },
    { id: "city_selection", label: "Washuk" },
    { id: "city_selection", label: "Zhob" },
    { id: "city_selection", label: "Ziarat" },
]

/**
 * Cities of pakistan
 */
export const CITIES = [ 
    { label: 'fedral', options: FEDRAL_CITIES },
    { label: 'punjab', options: PUNJAB_CITIES },
    { label: 'sindh', options: SINDH_CITIES },
    { label: 'kpk', options: KPK_CITIES },
    { label: 'balochistan', options: BALOCHISTAN_CITIES },
]

/**
 * Provinces of pakistan
 */
export const PROVINCES = [
    { id: 'province_selection', label: "Fedral" },
    { id: 'province_selection', label: "Punjab" },
    { id: 'province_selection', label: "Sindh" },
    { id: 'province_selection', label: "Khyber pakhtun khwa" },
    { id: 'province_selection', label: "Balochistan" },
]

/**
 * List of world countries
 */
export const COUTRIES = [
    { id: "country_selection", label: "Afghanistan" },
    { id: "country_selection", label: "Albania" },
    { id: "country_selection", label: "Algeria" },
    { id: "country_selection", label: "Andorra" },
    { id: "country_selection", label: "Angola" },
    { id: "country_selection", label: "Antigua & Deps" },
    { id: "country_selection", label: "Argentina" },
    { id: "country_selection", label: "Armenia" },
    { id: "country_selection", label: "Australia" },
    { id: "country_selection", label: "Austria" },
    { id: "country_selection", label: "Azerbaijan" },
    { id: "country_selection", label: "Bahamas" },
    { id: "country_selection", label: "Bahrain" },
    { id: "country_selection", label: "Bangladesh" },
    { id: "country_selection", label: "Barbados" },
    { id: "country_selection", label: "Belarus" },
    { id: "country_selection", label: "Belgium" },
    { id: "country_selection", label: "Belize" },
    { id: "country_selection", label: "Benin" },
    { id: "country_selection", label: "Bhutan" },
    { id: "country_selection", label: "Bolivia" },
    { id: "country_selection", label: "Bosnia Herzegovina" },
    { id: "country_selection", label: "Botswana" },
    { id: "country_selection", label: "Brazil" },
    { id: "country_selection", label: "Brunei" },
    { id: "country_selection", label: "Bulgaria" },
    { id: "country_selection", label: "Burkina" },
    { id: "country_selection", label: "Burundi" },
    { id: "country_selection", label: "Cambodia" },
    { id: "country_selection", label: "Cameroon" },
    { id: "country_selection", label: "Canada" },
    { id: "country_selection", label: "Cape Verde" },
    { id: "country_selection", label: "Central African Rep" },
    { id: "country_selection", label: "Chad" },
    { id: "country_selection", label: "Chile" },
    { id: "country_selection", label: "China" },
    { id: "country_selection", label: "Colombia" },
    { id: "country_selection", label: "Comoros" },
    { id: "country_selection", label: "Congo" },
    { id: "country_selection", label: "Congo {Democratic Rep}" },
    { id: "country_selection", label: "Costa Rica" },
    { id: "country_selection", label: "Croatia" },
    { id: "country_selection", label: "Cuba" },
    { id: "country_selection", label: "Cyprus" },
    { id: "country_selection", label: "Czech Republic" },
    { id: "country_selection", label: "Denmark" },
    { id: "country_selection", label: "Djibouti" },
    { id: "country_selection", label: "Dominica" },
    { id: "country_selection", label: "Dominican Republic" },
    { id: "country_selection", label: "East Timor" },
    { id: "country_selection", label: "Ecuador" },
    { id: "country_selection", label: "Egypt" },
    { id: "country_selection", label: "El Salvador" },
    { id: "country_selection", label: "Equatorial Guinea" },
    { id: "country_selection", label: "Eritrea" },
    { id: "country_selection", label: "Estonia" },
    { id: "country_selection", label: "Ethiopia" },
    { id: "country_selection", label: "Fiji" },
    { id: "country_selection", label: "Finland" },
    { id: "country_selection", label: "France" },
    { id: "country_selection", label: "Gabon" },
    { id: "country_selection", label: "Gambia" },
    { id: "country_selection", label: "Georgia" },
    { id: "country_selection", label: "Germany" },
    { id: "country_selection", label: "Ghana" },
    { id: "country_selection", label: "Greece" },
    { id: "country_selection", label: "Grenada" },
    { id: "country_selection", label: "Guatemala" },
    { id: "country_selection", label: "Guinea" },
    { id: "country_selection", label: "Guinea-Bissau" },
    { id: "country_selection", label: "Guyana" },
    { id: "country_selection", label: "Haiti" },
    { id: "country_selection", label: "Honduras" },
    { id: "country_selection", label: "Hungary" },
    { id: "country_selection", label: "Iceland" },
    { id: "country_selection", label: "India" },
    { id: "country_selection", label: "Indonesia" },
    { id: "country_selection", label: "Iran" },
    { id: "country_selection", label: "Iraq" },
    { id: "country_selection", label: "Ireland {Republic}" },
    { id: "country_selection", label: "Israel" },
    { id: "country_selection", label: "Italy" },
    { id: "country_selection", label: "Ivory Coast" },
    { id: "country_selection", label: "Jamaica" },
    { id: "country_selection", label: "Japan" },
    { id: "country_selection", label: "Jordan" },
    { id: "country_selection", label: "Kazakhstan" },
    { id: "country_selection", label: "Kenya" },
    { id: "country_selection", label: "Kiribati" },
    { id: "country_selection", label: "Korea North" },
    { id: "country_selection", label: "Korea South" },
    { id: "country_selection", label: "Kosovo" },
    { id: "country_selection", label: "Kuwait" },
    { id: "country_selection", label: "Kyrgyzstan" },
    { id: "country_selection", label: "Laos" },
    { id: "country_selection", label: "Latvia" },
    { id: "country_selection", label: "Lebanon" },
    { id: "country_selection", label: "Lesotho" },
    { id: "country_selection", label: "Liberia" },
    { id: "country_selection", label: "Libya" },
    { id: "country_selection", label: "Liechtenstein" },
    { id: "country_selection", label: "Lithuania" },
    { id: "country_selection", label: "Luxembourg" },
    { id: "country_selection", label: "Macedonia" },
    { id: "country_selection", label: "Madagascar" },
    { id: "country_selection", label: "Malawi" },
    { id: "country_selection", label: "Malaysia" },
    { id: "country_selection", label: "Maldives" },
    { id: "country_selection", label: "Mali" },
    { id: "country_selection", label: "Malta" },
    { id: "country_selection", label: "Marshall Islands" },
    { id: "country_selection", label: "Mauritania" },
    { id: "country_selection", label: "Mauritius" },
    { id: "country_selection", label: "Mexico" },
    { id: "country_selection", label: "Micronesia" },
    { id: "country_selection", label: "Moldova" },
    { id: "country_selection", label: "Monaco" },
    { id: "country_selection", label: "Mongolia" },
    { id: "country_selection", label: "Montenegro" },
    { id: "country_selection", label: "Morocco" },
    { id: "country_selection", label: "Mozambique" },
    { id: "country_selection", label: "Myanmar, {Burma}" },
    { id: "country_selection", label: "Namibia" },
    { id: "country_selection", label: "Nauru" },
    { id: "country_selection", label: "Nepal" },
    { id: "country_selection", label: "Netherlands" },
    { id: "country_selection", label: "New Zealand" },
    { id: "country_selection", label: "Nicaragua" },
    { id: "country_selection", label: "Niger" },
    { id: "country_selection", label: "Nigeria" },
    { id: "country_selection", label: "Norway" },
    { id: "country_selection", label: "Oman" },
    { id: "country_selection", label: "Pakistan" },
    { id: "country_selection", label: "Palau" },
    { id: "country_selection", label: "Panama" },
    { id: "country_selection", label: "Papua New Guinea" },
    { id: "country_selection", label: "Paraguay" },
    { id: "country_selection", label: "Peru" },
    { id: "country_selection", label: "Philippines" },
    { id: "country_selection", label: "Poland" },
    { id: "country_selection", label: "Portugal" },
    { id: "country_selection", label: "Qatar" },
    { id: "country_selection", label: "Romania" },
    { id: "country_selection", label: "Russian Federation" },
    { id: "country_selection", label: "Rwanda" },
    { id: "country_selection", label: "St Kitts & Nevis" },
    { id: "country_selection", label: "St Lucia" },
    { id: "country_selection", label: "Saint Vincent & the Grenadines" },
    { id: "country_selection", label: "Samoa" },
    { id: "country_selection", label: "San Marino" },
    { id: "country_selection", label: "Sao Tome & Principe" },
    { id: "country_selection", label: "Saudi Arabia" },
    { id: "country_selection", label: "Senegal" },
    { id: "country_selection", label: "Serbia" },
    { id: "country_selection", label: "Seychelles" },
    { id: "country_selection", label: "Sierra Leone" },
    { id: "country_selection", label: "Singapore" },
    { id: "country_selection", label: "Slovakia" },
    { id: "country_selection", label: "Slovenia" },
    { id: "country_selection", label: "Solomon Islands" },
    { id: "country_selection", label: "Somalia" },
    { id: "country_selection", label: "South Africa" },
    { id: "country_selection", label: "South Sudan" },
    { id: "country_selection", label: "Spain" },
    { id: "country_selection", label: "Sri Lanka" },
    { id: "country_selection", label: "Sudan" },
    { id: "country_selection", label: "Suriname" },
    { id: "country_selection", label: "Swaziland" },
    { id: "country_selection", label: "Sweden" },
    { id: "country_selection", label: "Switzerland" },
    { id: "country_selection", label: "Syria" },
    { id: "country_selection", label: "Taiwan" },
    { id: "country_selection", label: "Tajikistan" },
    { id: "country_selection", label: "Tanzania" },
    { id: "country_selection", label: "Thailand" },
    { id: "country_selection", label: "Togo" },
    { id: "country_selection", label: "Tonga" },
    { id: "country_selection", label: "Trinidad & Tobago" },
    { id: "country_selection", label: "Tunisia" },
    { id: "country_selection", label: "Turkey" },
    { id: "country_selection", label: "Turkmenistan" },
    { id: "country_selection", label: "Tuvalu" },
    { id: "country_selection", label: "Uganda" },
    { id: "country_selection", label: "Ukraine" },
    { id: "country_selection", label: "United Arab Emirates" },
    { id: "country_selection", label: "United Kingdom" },
    { id: "country_selection", label: "United States" },
    { id: "country_selection", label: "Uruguay" },
    { id: "country_selection", label: "Uzbekistan" },
    { id: "country_selection", label: "Vanuatu" },
    { id: "country_selection", label: "Vatican City" },
    { id: "country_selection", label: "Venezuela" },
    { id: "country_selection", label: "Vietnam" },
    { id: "country_selection", label: "Yemen" },
    { id: "country_selection", label: "Zambia" },
    { id: "country_selection", label: "Zimbabwe" },
]

export const HOURS24 = [
    { id: 'hour_selection', label: '00' },
    { id: 'hour_selection', label: '01' },
    { id: 'hour_selection', label: '02' },
    { id: 'hour_selection', label: '03' },
    { id: 'hour_selection', label: '04' },
    { id: 'hour_selection', label: '05' },
    { id: 'hour_selection', label: '06' },
    { id: 'hour_selection', label: '07' },
    { id: 'hour_selection', label: '08' },
    { id: 'hour_selection', label: '09' },
    { id: 'hour_selection', label: '10' },
    { id: 'hour_selection', label: '11' },
    { id: 'hour_selection', label: '12' },
    { id: 'hour_selection', label: '13' },
    { id: 'hour_selection', label: '14' },
    { id: 'hour_selection', label: '15' },
    { id: 'hour_selection', label: '16' },
    { id: 'hour_selection', label: '17' },
    { id: 'hour_selection', label: '18' },
    { id: 'hour_selection', label: '19' },
    { id: 'hour_selection', label: '20' },
    { id: 'hour_selection', label: '21' },
    { id: 'hour_selection', label: '22' },
    { id: 'hour_selection', label: '23' },
]

export const TIME_PERIOD = [
    { id: 'time_period_selection', label: 'AM' },
    { id: 'time_period_selection', label: 'PM' },
]

export const HOURS12 = [
    { id: 'hour_selection', label: '01' },
    { id: 'hour_selection', label: '02' },
    { id: 'hour_selection', label: '03' },
    { id: 'hour_selection', label: '04' },
    { id: 'hour_selection', label: '05' },
    { id: 'hour_selection', label: '06' },
    { id: 'hour_selection', label: '07' },
    { id: 'hour_selection', label: '08' },
    { id: 'hour_selection', label: '09' },
    { id: 'hour_selection', label: '10' },
    { id: 'hour_selection', label: '11' },
    { id: 'hour_selection', label: '12' },
]

export const MINS = [
    { id: 'min_selection', label: '00' },
    { id: 'min_selection', label: '01' },
    { id: 'min_selection', label: '02' },
    { id: 'min_selection', label: '03' },
    { id: 'min_selection', label: '04' },
    { id: 'min_selection', label: '05' },
    { id: 'min_selection', label: '06' },
    { id: 'min_selection', label: '07' },
    { id: 'min_selection', label: '08' },
    { id: 'min_selection', label: '09' },
    { id: 'min_selection', label: '10' },
    { id: 'min_selection', label: '11' },
    { id: 'min_selection', label: '12' },
    { id: 'min_selection', label: '13' },
    { id: 'min_selection', label: '14' },
    { id: 'min_selection', label: '15' },
    { id: 'min_selection', label: '16' },
    { id: 'min_selection', label: '17' },
    { id: 'min_selection', label: '18' },
    { id: 'min_selection', label: '19' },
    { id: 'min_selection', label: '20' },
    { id: 'min_selection', label: '21' },
    { id: 'min_selection', label: '22' },
    { id: 'min_selection', label: '23' },
    { id: 'min_selection', label: '24' },
    { id: 'min_selection', label: '25' },
    { id: 'min_selection', label: '26' },
    { id: 'min_selection', label: '27' },
    { id: 'min_selection', label: '28' },
    { id: 'min_selection', label: '29' },
    { id: 'min_selection', label: '30' },
    { id: 'min_selection', label: '31' },
    { id: 'min_selection', label: '32' },
    { id: 'min_selection', label: '33' },
    { id: 'min_selection', label: '34' },
    { id: 'min_selection', label: '35' },
    { id: 'min_selection', label: '36' },
    { id: 'min_selection', label: '37' },
    { id: 'min_selection', label: '38' },
    { id: 'min_selection', label: '39' },
    { id: 'min_selection', label: '40' },
    { id: 'min_selection', label: '41' },
    { id: 'min_selection', label: '42' },
    { id: 'min_selection', label: '43' },
    { id: 'min_selection', label: '44' },
    { id: 'min_selection', label: '45' },
    { id: 'min_selection', label: '46' },
    { id: 'min_selection', label: '47' },
    { id: 'min_selection', label: '48' },
    { id: 'min_selection', label: '49' },
    { id: 'min_selection', label: '50' },
    { id: 'min_selection', label: '51' },
    { id: 'min_selection', label: '52' },
    { id: 'min_selection', label: '53' },
    { id: 'min_selection', label: '54' },
    { id: 'min_selection', label: '55' },
    { id: 'min_selection', label: '56' },
    { id: 'min_selection', label: '57' },
    { id: 'min_selection', label: '58' },
    { id: 'min_selection', label: '59' },
]

export const MINS_BY_5 = [
    { id: 'min_selection', label: '00' },
    { id: 'min_selection', label: '05' },
    { id: 'min_selection', label: '10' },
    { id: 'min_selection', label: '15' },
    { id: 'min_selection', label: '20' },
    { id: 'min_selection', label: '25' },
    { id: 'min_selection', label: '30' },
    { id: 'min_selection', label: '35' },
    { id: 'min_selection', label: '40' },
    { id: 'min_selection', label: '45' },
    { id: 'min_selection', label: '50' },
    { id: 'min_selection', label: '55' },
]